export const SET_FILTERS_FORM_STATE = 'SET_FILTERS_FORM_STATE';

export const GET_FILTERS_REQUEST = 'GET_FILTERS_REQUEST';
export const GET_FILTERS_ERROR = 'GET_FILTERS_ERROR';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';